# Statistical Analysis of 30-Day Hospital Readmission
### Assessing Readmission Burden- Secondary Diagnosis, associated Factors, Statistial Significance and Effect Size.


## Purpose

This analysis examines the burden of 30-day hospital readmissions and evaluates whether selected factors differ between patients who were readmitted within 30 days and those who were not.

The analysis uses descriptive statistics and hypothesis testing to identify factors that show evidence of association with 30-day readmission. Effect-size measures are also calculated to distinguish statistically significant findings from associations that may have greater practical or analytical importance.

The resulting analysis table is used to support the Tableau Dashboard

## Business Questions

This analysis addresses four primary questions:
1. **Which continuous clinical and utilization variables differ between readmitted and non-readmitted patients?**
2. **Which categorical patient, admission, and hospital characteristics are associated with readmission?**
3. **Which statistically significant associations have meaningful effect sizes and may warrant further investigation or consideration in intervention planning?**

## Analytical Population

The analysis focuses on admissions with a **secondary diagnosis**, as defined in the prepared analytical dataset.

For clinical comparison analyses, patients with an outcome of 30-day readmission = 0 or 1 are included. Patients whose discharge status indicates death are excluded from analyses where comparison of post-discharge readmission risk is clinically inappropriate.

## Output

The final analytical dataset contains:

* Group-level descriptive statistics
* Statistical significance
* Percentage-point differences for categorical variables
* Cohen's d for continuous variables
* Cramér's V for categorical variables
* Direction of association
* Effect-size interpretation

The final table is exported for use in Tableau dashboard

## Statistical Methodology

### Analytical Approach

The analysis compares admissions with and without a 30-day readmission outcome using separate statistical methods for continuous and categorical variables.

### Continuous Variables

For continuous variables, the analysis reports:

* Mean among non-readmitted admissions
* Mean among readmitted admissions
* Mean difference
* Welch's independent-samples t-test
* p-value
* Cohen's d effect size
* Direction of the difference

Welch's t-test is used because it does not require the two groups to have equal variances.

### Categorical Variables

For categorical variables, the analysis reports:

* Distribution within the non-readmitted group
* Distribution within the readmitted group
* Percentage-point difference
* Chi-square test of independence
* p-value
* Cramér's V effect size
* Direction of the association

### Statistical Significance

A p-value below 0.05 is treated as statistically significant for the primary analysis.

Statistical significance is interpreted together with effect size rather than used as the sole criterion for identifying important factors.

### Effect Size

Effect sizes are included because large datasets can produce statistically significant results even when the practical difference is small.

For continuous variables:

# * |d| < 0.20 → Negligible
* |d| 0.20–<0.50 → Small
* |d| 0.50–<0.80 → Moderate
* |d| ≥ 0.80 → Large

For categorical variables:

* V < 0.10 → Negligible
* V 0.10–<0.30 → Small
* V 0.30–<0.50 → Moderate
* V ≥ 0.50 → Large

## Interpretation

These analyses identify **unadjusted associations** between individual variables and 30-day readmission.

They do not establish causality, and statistical significance does not imply clinical importance.

Variables identified here may be considered for further investigation, visualization, or inclusion in predictive modeling. Predictive modeling is performed separately using a modeling-specific dataset and methodology.

### Load Analytical Dataset

The analysis begins with the validated feature table prepared in BigQuery.

The table contains patient-level admission records and derived features used for downstream exploratory analysis, statistical analysis, Tableau visualization, and predictive modeling.

The statistical analysis does not perform raw-data cleaning or feature construction. Those activities were completed upstream in the SQL data-preparation workflow.

In [49]:
# ============================================================
# 1. LIBRARIES
# ============================================================

import pandas as pd
import numpy as np

from scipy import stats
from statsmodels.stats.multitest import multipletests

from google.colab import auth
from google.cloud import bigquery
from google.colab import files

In [50]:
# ============================================================
# 2. LOAD ANALYTICAL DATASET FROM BIGQUERY
# ============================================================

auth.authenticate_user()

client = bigquery.Client(
    project="healthcare-readmission-505214"
)

query = """
SELECT *
FROM `healthcare-readmission-505214.staging.fea_readmission_tableauV2`
"""

df = client.query(query).to_dataframe()

print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns):,}")

df.head()

Rows: 120,000
Columns: 79

,admission_id,patient_id,age,gender,patient_state,bpl_card,insurance_type,comorbidity_count,prev_admissions,admit_date,...,has_K70,has_P22,has_A09,has_A15,has_J45,has_S06,has_N39,has_S72,has_C50,has_A41
0,769a7a15-d6c8-437c-89e9-f74441f146d0,68c06f5e-6252-48d2-a9e7-557b790536f7,80,M,Telangana,True,Ayushman,3,2,2016-12-15,...,0,0,1,0,0,0,0,0,0,0
1,865b69f7-6dac-473f-a734-d73b829840f1,95cd61e5-3c8b-4602-a6f8-361d27e0bad1,7,M,Karnataka,True,Private,0,0,2023-07-23,...,0,0,1,0,0,0,0,0,0,0
2,7ab5c658-7805-4af7-8b9b-eced235a672f,d42c162b-38fe-4da7-9026-7f9cfb81cedd,40,F,Telangana,False,Ayushman,0,1,2017-09-03,...,0,0,0,0,0,0,0,0,0,1
3,67ad7851-3319-410f-b7a6-709ebab6e06d,2e47deb0-4a16-4f03-b6dc-5c46fe9e85fd,48,M,Maharashtra,True,None,0,0,2021-11-24,...,0,0,0,0,0,0,0,0,0,1
4,a6aa6af1-c712-4bbd-924b-20023b4ca060,e8779fad-cfe6-41c2-8a1d-2dc1732171af,36,M,Gujarat,True,Ayushman,0,0,2021-10-08,...,0,0,0,0,0,0,0,0,0,1

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 79 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   admission_id               120000 non-null  object
 1   patient_id                 120000 non-null  object
 2   age                        120000 non-null  Int64
 3   gender                     120000 non-null  object
 4   patient_state              120000 non-null  object
 5   bpl_card                   120000 non-null  boolean
 6   insurance_type             120000 non-null  object
 7   comorbidity_count          120000 non-null  Int64
 8   prev_admissions            120000 non-null  Int64
 9   admit_date                 120000 non-null  dbdate
 10  discharge_date             120000 non-null  dbdate
 11  los_days                   120000 non-null  Int64
 12  admit_type                 120000 non-null  object
 13  ward_type                  120000 non-null  object
 14  hospital_id                120000 non-null  object
 15  discharge_type             120000 non-null  object
 16  num_procedures             120000 non-null  Int64
 17  charlson_index             120000 non-null  Int64
 18  hba1c                      120000 non-null  float64
 19  creatinine                 120000 non-null  float64
 20  haemoglobin                120000 non-null  float64
 21  systolic_bp                120000 non-null  Int64
 22  hospital_name              120000 non-null  object
 23  hospital_state             120000 non-null  object
 24  tier                       120000 non-null  object
 25  beds                       120000 non-null  Int64
 26  teaching                   120000 non-null  boolean
 27  diagnosis_count            120000 non-null  Int64
 28  secondary_diagnosis_count  120000 non-null  Int64
 29  primary_icd10_code         120000 non-null  object
 30  primary_diag_desc          120000 non-null  object
 31  primary_diag_category      120000 non-null  object
 32  has_cardiovascular         120000 non-null  Int64
 33  has_endocrine              120000 non-null  Int64
 34  has_infectious             120000 non-null  Int64
 35  has_respiratory            120000 non-null  Int64
 36  has_gastrointestinal       120000 non-null  Int64
 37  has_neoplasm               120000 non-null  Int64
 38  has_neurological           120000 non-null  Int64
 39  has_injury                 120000 non-null  Int64
 40  has_genitourinary          120000 non-null  Int64
 41  has_obstetric              120000 non-null  Int64
 42  has_perinatal              120000 non-null  Int64
 43  readmitted_30d             120000 non-null  Int64
 44  readmitted_7d              120000 non-null  Int64
 45  has_E10                    120000 non-null  Int64
 46  has_E11                    120000 non-null  Int64
 47  has_E87                    120000 non-null  Int64
 48  has_I21                    120000 non-null  Int64
 49  has_I48                    120000 non-null  Int64
 50  has_I10                    120000 non-null  Int64
 51  has_I50                    120000 non-null  Int64
 52  has_N18                    120000 non-null  Int64
 53  has_K57                    120000 non-null  Int64
 54  has_G40                    120000 non-null  Int64
 55  has_K80                    120000 non-null  Int64
 56  has_G35                    120000 non-null  Int64
 57  has_J18                    120000 non-null  Int64
 58  has_J44                    120000 non-null  Int64
 59  has_C18                    120000 non-null  Int64
 60  has_I63                    120000 non-null  Int64
 61  has_C34                    120000 non-null  Int64
 62  has_J96                    120000 non-null  Int64
 63  has_T14                    120000 non-null  Int64
 64  has_B54                    120000 non-null  Int64
 65  has_O34                    120000 non-null  Int64
 66  has_A91                    120000 non-null  Int64
 67  has_O80                    120000 non-null  Int64
 68  has_P07                    120000 non-null  Int64
 69  has_K70                    120000 non-null  Int64
 70  has_P22                    120000 non-null  Int64
 71  has_A09                    120000 non-null  Int64
 72  has_A15                    120000 non-null  Int64
 73  has_J45                    120000 non-null  Int64
 74  has_S06                    120000 non-null  Int64
 75  has_N39                    120000 non-null  Int64
 76  has_S72                    120000 non-null  Int64
 77  has_C50                    120000 non-null  Int64
 78  has_A41                    120000 non-null  Int64
dtypes: Int64(57), boolean(2), dbdate(2), float64(3), object(15)
memory usage: 77.5+ MB

In [52]:
# ============================================================
# 3. DEFINE DIAGNOSIS TYPE
# ============================================================

df["diag_type"] = np.where(
    df["secondary_diagnosis_count"] > 0,
    "Secondary",
    "Primary"
)

df["diag_type"].value_counts()

diag_type
Secondary    77128
Primary      42872
Name: count, dtype: int64

In [53]:
# ============================================================
# 4. DEFINE ANALYTICAL POPULATION
# ============================================================

analysis_df = df[
    (df["diag_type"] == "Secondary") &
    (df["readmitted_30d"].isin([0, 1])) &
    (df["discharge_type"] != "Expired")
].copy()

print(f"Original admissions: {len(df):,}")

print(
    f"Secondary-diagnosis admissions: "
    f"{(df['diag_type'] == 'Secondary').sum():,}"
)

print(
    f"Excluded expired admissions: "
    f"{(df['discharge_type'] == 'Expired').sum():,}"
)

print(
    f"Analytical population: "
    f"{len(analysis_df):,}"
)

Original admissions: 120,000
Secondary-diagnosis admissions: 77,128
Excluded expired admissions: 7,413
Analytical population: 72,532

In [54]:
# ============================================================
# 5. READMISSION OUTCOME CHECK
# ============================================================

readmission_counts = (
    analysis_df["readmitted_30d"]
    .value_counts()
    .sort_index()
)

print("30-day readmission counts:")
print(readmission_counts)

30-day readmission counts:
readmitted_30d
0    60948
1    11584
Name: count, dtype: Int64

In [55]:
# ============================================================
# 6. READMISSION BURDEN
# ============================================================

total_admissions = len(analysis_df)

readmitted = (
    analysis_df["readmitted_30d"] == 1
).sum()

not_readmitted = (
    analysis_df["readmitted_30d"] == 0
).sum()

readmission_rate = (
    readmitted / total_admissions * 100
)

print(f"Total analytical admissions: {total_admissions:,}")
print(f"Readmitted within 30 days: {readmitted:,}")
print(f"Not readmitted: {not_readmitted:,}")
print(f"30-day readmission rate: {readmission_rate:.2f}%")

Total analytical admissions: 72,532
Readmitted within 30 days: 11,584
Not readmitted: 60,948
30-day readmission rate: 15.97%

In [56]:
# ============================================================
# 7. VARIABLE DEFINITIONS
# ============================================================

continuous_vars = [
    "age",
    "comorbidity_count",
    "prev_admissions",
    "los_days",
    "num_procedures",
    "charlson_index",
    "hba1c",
    "creatinine",
    "haemoglobin",
    "systolic_bp",
    "diagnosis_count"
]

categorical_vars = [
    "gender",
    "patient_state",
    "insurance_type",
    "admit_type",
    "ward_type",
    "discharge_type",
    "hospital_name",
    "hospital_state",
    "tier",
    "teaching",
    "bpl_card",
    "primary_diag_category"
]

In [57]:
# ============================================================
# 8. TABLEAU-FRIENDLY VARIABLE NAMES
# ============================================================

variable_labels = {

    # Continuous
    "age": "Age",
    "comorbidity_count": "Comorbidity count",
    "prev_admissions": "Previous admissions",
    "los_days": "Length of stay",
    "num_procedures": "Procedures",
    "charlson_index": "Charlson index",
    "hba1c": "HbA1c",
    "creatinine": "Creatinine",
    "haemoglobin": "Haemoglobin",
    "systolic_bp": "Systolic blood pressure",
    "diagnosis_count": "Diagnosis count",

    # Categorical
    "gender": "Gender",
    "patient_state": "Patient state",
    "insurance_type": "Insurance type",
    "admit_type": "Admission type",
    "ward_type": "Ward type",
    "discharge_type": "Discharge type",
    "hospital_name": "Hospital",
    "hospital_state": "Hospital state",
    "tier": "Hospital tier",
    "teaching": "Teaching hospital",
    "bpl_card": "BPL card",
    "primary_diag_category": "Primary diagnosis category"
}

In [58]:
# ============================================================
# 9. UNITS
# ============================================================

units = {

    "age": "years",
    "comorbidity_count": "count",
    "prev_admissions": "count",
    "los_days": "days",
    "num_procedures": "count",
    "charlson_index": "score",
    "hba1c": "%",
    "creatinine": "mg/dL",
    "haemoglobin": "g/dL",
    "systolic_bp": "mmHg",
    "diagnosis_count": "count"
}

In [59]:
# ============================================================
# 10. EFFECT-SIZE INTERPRETATION
# ============================================================

def classify_cohens_d(d):
    """
    Interpret Cohen's d using conventional magnitude thresholds.
    Classification is intended for dashboard interpretation
    and should be considered alongside clinical context.
    """

    if pd.isna(d):
        return np.nan

    d_abs = abs(d)

    if d_abs >= 0.80:
        return "Large"
    elif d_abs >= 0.50:
        return "Moderate"
    elif d_abs >= 0.20:
        return "Small"
    else:
        return "Negligible"


def classify_cramers_v(v):
    """
    Interpret Cramér's V using conventional magnitude thresholds.
    Classification is intended for dashboard interpretation
    and should be considered alongside context.
    """

    if pd.isna(v):
        return np.nan

    v_abs = abs(v)

    if v_abs >= 0.50:
        return "Large"
    elif v_abs >= 0.30:
        return "Moderate"
    elif v_abs >= 0.10:
        return "Small"
    else:
        return "Negligible"

In [60]:
# ============================================================
# 11. CONTINUOUS VARIABLE ANALYSIS
# ============================================================

continuous_rows = []

for var in continuous_vars:

    # --------------------------------------------------------
    # Split observations by readmission status
    # --------------------------------------------------------

    not_readmitted_values = (
        analysis_df.loc[
            analysis_df["readmitted_30d"] == 0,
            var
        ]
        .dropna()
    )

    readmitted_values = (
        analysis_df.loc[
            analysis_df["readmitted_30d"] == 1,
            var
        ]
        .dropna()
    )

    # --------------------------------------------------------
    # Sample sizes
    # --------------------------------------------------------

    n_not = len(not_readmitted_values)
    n_read = len(readmitted_values)

    # --------------------------------------------------------
    # Group means
    # --------------------------------------------------------

    mean_not = not_readmitted_values.mean()
    mean_read = readmitted_values.mean()

    # Difference = Readmitted - Not Readmitted
    difference = mean_read - mean_not

    # --------------------------------------------------------
    # Welch's independent-samples t-test
    # --------------------------------------------------------

    t_stat, p_value = stats.ttest_ind(
        not_readmitted_values,
        readmitted_values,
        equal_var=False,
        nan_policy="omit"
    )

    # --------------------------------------------------------
    # Cohen's d
    # --------------------------------------------------------

    sd_not = not_readmitted_values.std(ddof=1)
    sd_read = readmitted_values.std(ddof=1)

    if n_not > 1 and n_read > 1:

        pooled_sd = np.sqrt(
            (
                (n_not - 1) * sd_not**2 +
                (n_read - 1) * sd_read**2
            )
            /
            (n_not + n_read - 2)
        )

    else:
        pooled_sd = np.nan

    if pd.isna(pooled_sd) or pooled_sd == 0:
        cohens_d = np.nan
    else:
        cohens_d = difference / pooled_sd

    # --------------------------------------------------------
    # Direction
    # --------------------------------------------------------

    if difference > 0:
        direction = "Higher in readmitted"
    elif difference < 0:
        direction = "Lower in readmitted"
    else:
        direction = "No difference"

    # --------------------------------------------------------
    # Add result
    # --------------------------------------------------------

    continuous_rows.append({

        "DataType": "Continuous",
        "Variable": variable_labels.get(var, var),
        "Categorical": np.nan,

        "Not Readmitted": mean_not,
        "Readmitted": mean_read,
        "Difference": difference,

        "Unit": units.get(var, ""),

        "N Not Readmitted": n_not,
        "N Readmitted": n_read,

        "Test": "Welch's t-test",

        "Effect Size Type": "Cohen's d",
        "Effect Size": cohens_d,
        "Effect Size Interpretation":
            classify_cohens_d(cohens_d),

        "Direction": direction,

        "P-value": p_value
    })


continuous_table = pd.DataFrame(continuous_rows)

continuous_table

,DataType,Variable,Categorical,Not Readmitted,Readmitted,Difference,Unit,N Not Readmitted,N Readmitted,Test,Effect Size Type,Effect Size,Effect Size Interpretation,Direction,P-value
0,Continuous,Age,NaN,56.646666,62.796961,6.150295,years,60948,11584,Welch's t-test,Cohen's d,0.391782,Small,Higher in readmitted,0.000000e+00
1,Continuous,Comorbidity count,NaN,2.118101,2.855490,0.737390,count,60948,11584,Welch's t-test,Cohen's d,0.564452,Moderate,Higher in readmitted,0.000000e+00
2,Continuous,Previous admissions,NaN,1.106976,1.569233,0.462257,count,60948,11584,Welch's t-test,Cohen's d,0.395497,Small,Higher in readmitted,1.883977e-246
3,Continuous,Length of stay,NaN,6.526104,10.331319,3.805215,days,60948,11584,Welch's t-test,Cohen's d,0.675005,Moderate,Higher in readmitted,0.000000e+00
4,Continuous,Procedures,NaN,1.868609,2.460031,0.591422,count,60948,11584,Welch's t-test,Cohen's d,0.364918,Small,Higher in readmitted,1.442982e-221
5,Continuous,Charlson index,NaN,2.421408,3.195701,0.774293,score,60948,11584,Welch's t-test,Cohen's d,0.509664,Moderate,Higher in readmitted,0.000000e+00
6,Continuous,HbA1c,NaN,5.883885,5.822721,-0.061164,%,60948,11584,Welch's t-test,Cohen's d,-0.057191,Negligible,Lower in readmitted,2.001942e-09
7,Continuous,Creatinine,NaN,1.078571,1.134487,0.055916,mg/dL,60948,11584,Welch's t-test,Cohen's d,0.058881,Negligible,Higher in readmitted,2.167692e-07
8,Continuous,Haemoglobin,NaN,11.478938,10.779290,-0.699647,g/dL,60948,11584,Welch's t-test,Cohen's d,-0.330622,Small,Lower in readmitted,1.795173e-223
9,Continuous,Systolic blood pressure,NaN,137.117018,141.621547,4.504529,mmHg,60948,11584,Welch's t-test,Cohen's d,0.218281,Small,Higher in readmitted,1.016940e-97
10,Continuous,Diagnosis count,NaN,2.904361,3.294631,0.390269,count,60948,11584,Welch's t-test,Cohen's d,0.470275,Small,Higher in readmitted,0.000000e+00

In [61]:
# ============================================================
# 12. CATEGORICAL VARIABLE ANALYSIS
# ============================================================

categorical_rows = []

for var in categorical_vars:

    # --------------------------------------------------------
    # Remove missing values for the variable being tested
    # --------------------------------------------------------

    temp = (
        analysis_df[
            [var, "readmitted_30d"]
        ]
        .dropna()
        .copy()
    )

    # --------------------------------------------------------
    # Create contingency table
    # Rows = categories
    # Columns = readmission status
    # --------------------------------------------------------

    contingency = pd.crosstab(
        temp[var],
        temp["readmitted_30d"]
    )

    # Make sure both outcome groups exist
    if 0 not in contingency.columns:
        contingency[0] = 0

    if 1 not in contingency.columns:
        contingency[1] = 0

    contingency = contingency[[0, 1]]

    # --------------------------------------------------------
    # Chi-square test
    # --------------------------------------------------------

    chi2, p_value, dof, expected = stats.chi2_contingency(
        contingency
    )

    # --------------------------------------------------------
    # Expected-frequency quality check
    # --------------------------------------------------------

    expected_flat = expected.flatten()

    min_expected = expected_flat.min()

    pct_expected_below_5 = (
        (expected_flat < 5).mean() * 100
    )

    # --------------------------------------------------------
    # Cramér's V
    # --------------------------------------------------------

    n = contingency.to_numpy().sum()

    r, k = contingency.shape

    min_dim = min(r - 1, k - 1)

    if min_dim == 0 or n == 0:
        cramers_v = np.nan
    else:
        cramers_v = np.sqrt(
            chi2 / (n * min_dim)
        )

    effect_size = classify_cramers_v(cramers_v)

    # --------------------------------------------------------
    # Percentage distribution within each outcome group
    # --------------------------------------------------------

    pct = contingency.div(
        contingency.sum(axis=0),
        axis=1
    ) * 100

    # --------------------------------------------------------
    # Create one row per category
    # --------------------------------------------------------

    for category in contingency.index:

        not_pct = pct.loc[category, 0]
        read_pct = pct.loc[category, 1]

        # Difference = Readmitted % - Not Readmitted %
        difference = read_pct - not_pct

        if difference > 0:
            direction = "Higher in readmitted"
        elif difference < 0:
            direction = "Lower in readmitted"
        else:
            direction = "No difference"

        categorical_rows.append({

            "DataType": "Categorical",
            "Variable": variable_labels.get(var, var),
            "Categorical": category,

            "Not Readmitted": not_pct,
            "Readmitted": read_pct,
            "Difference": difference,

            "Unit": "percentage points",

            "N Not Readmitted": contingency.loc[category, 0],
            "N Readmitted": contingency.loc[category, 1],

            "Test": "Chi-square",

            "Effect Size Type": "Cramér's V",
            "Effect Size": cramers_v,
            "Effect Size Interpretation": effect_size,

            "Direction": direction,

            "P-value": p_value,

            "Minimum Expected Count": min_expected,
            "Percent Expected Counts <5":
                pct_expected_below_5
        })


categorical_table = pd.DataFrame(categorical_rows)

categorical_table.head(30)

,DataType,Variable,Categorical,Not Readmitted,Readmitted,Difference,Unit,N Not Readmitted,N Readmitted,Test,Effect Size Type,Effect Size,Effect Size Interpretation,Direction,P-value,Minimum Expected Count,Percent Expected Counts <5
0,Categorical,Gender,F,47.558575,47.056285,-0.502290,percentage points,28986,5451,Chi-square,Cramér's V,0.003742,Negligible,Lower in readmitted,6.018191e-01,119.302487,0.0
1,Categorical,Gender,M,51.415961,51.890539,0.474578,percentage points,31337,6011,Chi-square,Cramér's V,0.003742,Negligible,Higher in readmitted,6.018191e-01,119.302487,0.0
2,Categorical,Gender,Other,1.025464,1.053177,0.027712,percentage points,625,122,Chi-square,Cramér's V,0.003742,Negligible,Higher in readmitted,6.018191e-01,119.302487,0.0
3,Categorical,Patient state,Andhra Pradesh,6.725405,6.155041,-0.570364,percentage points,4099,713,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
4,Categorical,Patient state,Bihar,3.352038,3.271754,-0.080284,percentage points,2043,379,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
5,Categorical,Patient state,Gujarat,6.868150,6.750691,-0.117459,percentage points,4186,782,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
6,Categorical,Patient state,Haryana,4.809018,4.730663,-0.078355,percentage points,2931,548,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
7,Categorical,Patient state,Karnataka,8.387478,8.347721,-0.039757,percentage points,5112,967,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
8,Categorical,Patient state,Kerala,5.809871,5.792472,-0.017398,percentage points,3541,671,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
9,Categorical,Patient state,Madhya Pradesh,4.866444,5.326312,0.459869,percentage points,2966,617,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
10,Categorical,Patient state,Maharashtra,11.107830,10.773481,-0.334349,percentage points,6770,1248,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
11,Categorical,Patient state,Odisha,3.808164,3.927831,0.119667,percentage points,2321,455,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
12,Categorical,Patient state,Punjab,4.082168,4.126381,0.044213,percentage points,2488,478,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
13,Categorical,Patient state,Rajasthan,5.594933,5.559392,-0.035541,percentage points,3410,644,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
14,Categorical,Patient state,Tamil Nadu,9.166831,9.487224,0.320393,percentage points,5587,1099,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
15,Categorical,Patient state,Telangana,7.293102,7.527624,0.234522,percentage points,4445,872,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
16,Categorical,Patient state,Uttar Pradesh,10.362932,10.462707,0.099775,percentage points,6316,1212,Chi-square,Cramér's V,0.013283,Negligible,Higher in readmitted,5.425475e-01,386.814758,0.0
17,Categorical,Patient state,West Bengal,7.765636,7.760704,-0.004932,percentage points,4733,899,Chi-square,Cramér's V,0.013283,Negligible,Lower in readmitted,5.425475e-01,386.814758,0.0
18,Categorical,Insurance type,Ayushman,29.129750,35.359116,6.229366,percentage points,17754,4096,Chi-square,Cramér's V,0.064462,Negligible,Higher in readmitted,4.971046e-65,1936.948547,0.0
19,Categorical,Insurance type,ESI,16.630570,17.196133,0.565562,percentage points,10136,1992,Chi-square,Cramér's V,0.064462,Negligible,Higher in readmitted,4.971046e-65,1936.948547,0.0
20,Categorical,Insurance type,None,27.288836,27.296271,0.007434,percentage points,16632,3162,Chi-square,Cramér's V,0.064462,Negligible,Higher in readmitted,4.971046e-65,1936.948547,0.0
21,Categorical,Insurance type,Private,26.950843,20.148481,-6.802363,percentage points,16426,2334,Chi-square,Cramér's V,0.064462,Negligible,Lower in readmitted,4.971046e-65,1936.948547,0.0
22,Categorical,Admission type,Elective,33.097066,22.168508,-10.928558,percentage points,20172,2568,Chi-square,Cramér's V,0.119912,Small,Lower in readmitted,3.384434e-227,1497.270170,0.0
23,Categorical,Admission type,Emergency,53.130538,69.362914,16.232377,percentage points,32382,8035,Chi-square,Cramér's V,0.119912,Small,Higher in readmitted,3.384434e-227,1497.270170,0.0
24,Categorical,Admission type,OPD,13.772396,8.468577,-5.303819,percentage points,8394,981,Chi-square,Cramér's V,0.119912,Small,Lower in readmitted,3.384434e-227,1497.270170,0.0
25,Categorical,Ward type,General,66.084203,42.282459,-23.801744,percentage points,40277,4898,Chi-square,Cramér's V,0.204948,Small,Lower in readmitted,0.000000e+00,430.255556,0.0
26,Categorical,Ward type,HDU,14.371267,15.659530,1.288263,percentage points,8759,1814,Chi-square,Cramér's V,0.204948,Small,Higher in readmitted,0.000000e+00,430.255556,0.0
27,Categorical,Ward type,ICU,16.286014,35.946133,19.660118,percentage points,9926,4164,Chi-square,Cramér's V,0.204948,Small,Higher in readmitted,0.000000e+00,430.255556,0.0
28,Categorical,Ward type,NICU,3.258515,6.111878,2.853363,percentage points,1986,708,Chi-square,Cramér's V,0.204948,Small,Higher in readmitted,0.000000e+00,430.255556,0.0
29,Categorical,Discharge type,LAMA,12.876551,19.475138,6.598588,percentage points,7848,2256,Chi-square,Cramér's V,0.069844,Negligible,Higher in readmitted,1.475801e-77,996.423317,0.0

In [62]:
# ============================================================
# 13. MULTIPLE-COMPARISON ADJUSTMENT
#     Benjamini-Hochberg False Discovery Rate (FDR)
# ============================================================

# ------------------------------------------------------------
# Continuous variables
# Each variable represents one hypothesis test
# ------------------------------------------------------------

continuous_table["Adjusted P-value"] = multipletests(
    continuous_table["P-value"],
    method="fdr_bh"
)[1]

continuous_table["Adjusted Significant"] = np.where(
    continuous_table["Adjusted P-value"] < 0.05,
    "Yes",
    "No"
)


# ------------------------------------------------------------
# Categorical variables
# Adjust one p-value per categorical variable
# ------------------------------------------------------------

categorical_pvalues = (
    categorical_table[
        ["Variable", "P-value"]
    ]
    .drop_duplicates(subset="Variable")
    .copy()
)

categorical_pvalues["Adjusted P-value"] = multipletests(
    categorical_pvalues["P-value"],
    method="fdr_bh"
)[1]

categorical_pvalues["Adjusted Significant"] = np.where(
    categorical_pvalues["Adjusted P-value"] < 0.05,
    "Yes",
    "No"
)


# ------------------------------------------------------------
# Merge adjusted results back onto category rows
# ------------------------------------------------------------

categorical_table = categorical_table.drop(
    columns=[
        "Adjusted P-value",
        "Adjusted Significant"
    ],
    errors="ignore"
)

categorical_table = categorical_table.merge(
    categorical_pvalues,
    on=["Variable", "P-value"],
    how="left"
)

In [63]:
# ============================================================
# 14. COMBINE ANALYSIS RESULTS
# ============================================================

clinical_analysis_table = pd.concat(
    [
        continuous_table,
        categorical_table
    ],
    ignore_index=True
)

print(
    f"Combined analytical table: "
    f"{clinical_analysis_table.shape[0]:,} rows × "
    f"{clinical_analysis_table.shape[1]:,} columns"
)

Combined analytical table: 109 rows × 19 columns

In [64]:
# ============================================================
# 15. ORDER VARIABLES
# ============================================================

variable_order = (
    [variable_labels[v] for v in continuous_vars]
    +
    [variable_labels[v] for v in categorical_vars]
)

clinical_analysis_table["Variable"] = pd.Categorical(
    clinical_analysis_table["Variable"],
    categories=variable_order,
    ordered=True
)

clinical_analysis_table = (
    clinical_analysis_table
    .sort_values(
        ["DataType", "Variable", "Categorical"],
        na_position="first"
    )
    .reset_index(drop=True)
)

In [65]:
# ============================================================
# 16. CREATE DISPLAY TABLE
# ============================================================

display_table = clinical_analysis_table.copy()

display_table["Not Readmitted"] = (
    display_table["Not Readmitted"].round(2)
)

display_table["Readmitted"] = (
    display_table["Readmitted"].round(2)
)

display_table["Difference"] = (
    display_table["Difference"].round(2)
)

display_table["Effect Size"] = (
    display_table["Effect Size"].round(3)
)

display_table["P-value"] = (
    display_table["P-value"].round(6)
)

display_table["Adjusted P-value"] = (
    display_table["Adjusted P-value"].round(6)
)

display_table.head(30)

,DataType,Variable,Categorical,Not Readmitted,Readmitted,Difference,Unit,N Not Readmitted,N Readmitted,Test,Effect Size Type,Effect Size,Effect Size Interpretation,Direction,P-value,Adjusted P-value,Adjusted Significant,Minimum Expected Count,Percent Expected Counts <5
0,Categorical,Gender,F,47.56,47.06,-0.50,percentage points,28986,5451,Chi-square,Cramér's V,0.004,Negligible,Lower in readmitted,0.601819,0.656530,No,119.302487,0.0
1,Categorical,Gender,M,51.42,51.89,0.47,percentage points,31337,6011,Chi-square,Cramér's V,0.004,Negligible,Higher in readmitted,0.601819,0.656530,No,119.302487,0.0
2,Categorical,Gender,Other,1.03,1.05,0.03,percentage points,625,122,Chi-square,Cramér's V,0.004,Negligible,Higher in readmitted,0.601819,0.656530,No,119.302487,0.0
3,Categorical,Patient state,Andhra Pradesh,6.73,6.16,-0.57,percentage points,4099,713,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
4,Categorical,Patient state,Bihar,3.35,3.27,-0.08,percentage points,2043,379,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
5,Categorical,Patient state,Gujarat,6.87,6.75,-0.12,percentage points,4186,782,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
6,Categorical,Patient state,Haryana,4.81,4.73,-0.08,percentage points,2931,548,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
7,Categorical,Patient state,Karnataka,8.39,8.35,-0.04,percentage points,5112,967,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
8,Categorical,Patient state,Kerala,5.81,5.79,-0.02,percentage points,3541,671,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
9,Categorical,Patient state,Madhya Pradesh,4.87,5.33,0.46,percentage points,2966,617,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
10,Categorical,Patient state,Maharashtra,11.11,10.77,-0.33,percentage points,6770,1248,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
11,Categorical,Patient state,Odisha,3.81,3.93,0.12,percentage points,2321,455,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
12,Categorical,Patient state,Punjab,4.08,4.13,0.04,percentage points,2488,478,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
13,Categorical,Patient state,Rajasthan,5.59,5.56,-0.04,percentage points,3410,644,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
14,Categorical,Patient state,Tamil Nadu,9.17,9.49,0.32,percentage points,5587,1099,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
15,Categorical,Patient state,Telangana,7.29,7.53,0.23,percentage points,4445,872,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
16,Categorical,Patient state,Uttar Pradesh,10.36,10.46,0.10,percentage points,6316,1212,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No,386.814758,0.0
17,Categorical,Patient state,West Bengal,7.77,7.76,-0.00,percentage points,4733,899,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No,386.814758,0.0
18,Categorical,Insurance type,Ayushman,29.13,35.36,6.23,percentage points,17754,4096,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes,1936.948547,0.0
19,Categorical,Insurance type,ESI,16.63,17.20,0.57,percentage points,10136,1992,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes,1936.948547,0.0
20,Categorical,Insurance type,None,27.29,27.30,0.01,percentage points,16632,3162,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes,1936.948547,0.0
21,Categorical,Insurance type,Private,26.95,20.15,-6.80,percentage points,16426,2334,Chi-square,Cramér's V,0.064,Negligible,Lower in readmitted,0.000000,0.000000,Yes,1936.948547,0.0
22,Categorical,Admission type,Elective,33.10,22.17,-10.93,percentage points,20172,2568,Chi-square,Cramér's V,0.120,Small,Lower in readmitted,0.000000,0.000000,Yes,1497.270170,0.0
23,Categorical,Admission type,Emergency,53.13,69.36,16.23,percentage points,32382,8035,Chi-square,Cramér's V,0.120,Small,Higher in readmitted,0.000000,0.000000,Yes,1497.270170,0.0
24,Categorical,Admission type,OPD,13.77,8.47,-5.30,percentage points,8394,981,Chi-square,Cramér's V,0.120,Small,Lower in readmitted,0.000000,0.000000,Yes,1497.270170,0.0
25,Categorical,Ward type,General,66.08,42.28,-23.80,percentage points,40277,4898,Chi-square,Cramér's V,0.205,Small,Lower in readmitted,0.000000,0.000000,Yes,430.255556,0.0
26,Categorical,Ward type,HDU,14.37,15.66,1.29,percentage points,8759,1814,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes,430.255556,0.0
27,Categorical,Ward type,ICU,16.29,35.95,19.66,percentage points,9926,4164,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes,430.255556,0.0
28,Categorical,Ward type,NICU,3.26,6.11,2.85,percentage points,1986,708,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes,430.255556,0.0
29,Categorical,Discharge type,LAMA,12.88,19.48,6.60,percentage points,7848,2256,Chi-square,Cramér's V,0.070,Negligible,Higher in readmitted,0.000000,0.000000,Yes,996.423317,0.0

In [66]:
# ============================================================
# 17. CONTINUOUS RESULTS
# ============================================================

continuous_display = display_table[
    display_table["DataType"] == "Continuous"
][
    [
        "Variable",
        "Not Readmitted",
        "Readmitted",
        "Difference",
        "Unit",
        "Test",
        "Effect Size Type",
        "Effect Size",
        "Effect Size Interpretation",
        "Direction",
        "P-value",
        "Adjusted P-value",
        "Adjusted Significant"
    ]
]

display(continuous_display)

,Variable,Not Readmitted,Readmitted,Difference,Unit,Test,Effect Size Type,Effect Size,Effect Size Interpretation,Direction,P-value,Adjusted P-value,Adjusted Significant
98,Age,56.65,62.80,6.15,years,Welch's t-test,Cohen's d,0.392,Small,Higher in readmitted,0.0,0.0,Yes
99,Comorbidity count,2.12,2.86,0.74,count,Welch's t-test,Cohen's d,0.564,Moderate,Higher in readmitted,0.0,0.0,Yes
100,Previous admissions,1.11,1.57,0.46,count,Welch's t-test,Cohen's d,0.395,Small,Higher in readmitted,0.0,0.0,Yes
101,Length of stay,6.53,10.33,3.81,days,Welch's t-test,Cohen's d,0.675,Moderate,Higher in readmitted,0.0,0.0,Yes
102,Procedures,1.87,2.46,0.59,count,Welch's t-test,Cohen's d,0.365,Small,Higher in readmitted,0.0,0.0,Yes
103,Charlson index,2.42,3.20,0.77,score,Welch's t-test,Cohen's d,0.510,Moderate,Higher in readmitted,0.0,0.0,Yes
104,HbA1c,5.88,5.82,-0.06,%,Welch's t-test,Cohen's d,-0.057,Negligible,Lower in readmitted,0.0,0.0,Yes
105,Creatinine,1.08,1.13,0.06,mg/dL,Welch's t-test,Cohen's d,0.059,Negligible,Higher in readmitted,0.0,0.0,Yes
106,Haemoglobin,11.48,10.78,-0.70,g/dL,Welch's t-test,Cohen's d,-0.331,Small,Lower in readmitted,0.0,0.0,Yes
107,Systolic blood pressure,137.12,141.62,4.50,mmHg,Welch's t-test,Cohen's d,0.218,Small,Higher in readmitted,0.0,0.0,Yes
108,Diagnosis count,2.90,3.29,0.39,count,Welch's t-test,Cohen's d,0.470,Small,Higher in readmitted,0.0,0.0,Yes

In [67]:
# ============================================================
# 18. CATEGORICAL RESULTS
# ============================================================

categorical_display = display_table[
    display_table["DataType"] == "Categorical"
][
    [
        "Variable",
        "Categorical",
        "Not Readmitted",
        "Readmitted",
        "Difference",
        "Test",
        "Effect Size Type",
        "Effect Size",
        "Effect Size Interpretation",
        "Direction",
        "P-value",
        "Adjusted P-value",
        "Adjusted Significant"
    ]
]

display(categorical_display.head(50))

,Variable,Categorical,Not Readmitted,Readmitted,Difference,Test,Effect Size Type,Effect Size,Effect Size Interpretation,Direction,P-value,Adjusted P-value,Adjusted Significant
0,Gender,F,47.56,47.06,-0.50,Chi-square,Cramér's V,0.004,Negligible,Lower in readmitted,0.601819,0.656530,No
1,Gender,M,51.42,51.89,0.47,Chi-square,Cramér's V,0.004,Negligible,Higher in readmitted,0.601819,0.656530,No
2,Gender,Other,1.03,1.05,0.03,Chi-square,Cramér's V,0.004,Negligible,Higher in readmitted,0.601819,0.656530,No
3,Patient state,Andhra Pradesh,6.73,6.16,-0.57,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
4,Patient state,Bihar,3.35,3.27,-0.08,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
5,Patient state,Gujarat,6.87,6.75,-0.12,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
6,Patient state,Haryana,4.81,4.73,-0.08,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
7,Patient state,Karnataka,8.39,8.35,-0.04,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
8,Patient state,Kerala,5.81,5.79,-0.02,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
9,Patient state,Madhya Pradesh,4.87,5.33,0.46,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
10,Patient state,Maharashtra,11.11,10.77,-0.33,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
11,Patient state,Odisha,3.81,3.93,0.12,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
12,Patient state,Punjab,4.08,4.13,0.04,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
13,Patient state,Rajasthan,5.59,5.56,-0.04,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
14,Patient state,Tamil Nadu,9.17,9.49,0.32,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
15,Patient state,Telangana,7.29,7.53,0.23,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
16,Patient state,Uttar Pradesh,10.36,10.46,0.10,Chi-square,Cramér's V,0.013,Negligible,Higher in readmitted,0.542547,0.651057,No
17,Patient state,West Bengal,7.77,7.76,-0.00,Chi-square,Cramér's V,0.013,Negligible,Lower in readmitted,0.542547,0.651057,No
18,Insurance type,Ayushman,29.13,35.36,6.23,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes
19,Insurance type,ESI,16.63,17.20,0.57,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes
20,Insurance type,None,27.29,27.30,0.01,Chi-square,Cramér's V,0.064,Negligible,Higher in readmitted,0.000000,0.000000,Yes
21,Insurance type,Private,26.95,20.15,-6.80,Chi-square,Cramér's V,0.064,Negligible,Lower in readmitted,0.000000,0.000000,Yes
22,Admission type,Elective,33.10,22.17,-10.93,Chi-square,Cramér's V,0.120,Small,Lower in readmitted,0.000000,0.000000,Yes
23,Admission type,Emergency,53.13,69.36,16.23,Chi-square,Cramér's V,0.120,Small,Higher in readmitted,0.000000,0.000000,Yes
24,Admission type,OPD,13.77,8.47,-5.30,Chi-square,Cramér's V,0.120,Small,Lower in readmitted,0.000000,0.000000,Yes
25,Ward type,General,66.08,42.28,-23.80,Chi-square,Cramér's V,0.205,Small,Lower in readmitted,0.000000,0.000000,Yes
26,Ward type,HDU,14.37,15.66,1.29,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes
27,Ward type,ICU,16.29,35.95,19.66,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes
28,Ward type,NICU,3.26,6.11,2.85,Chi-square,Cramér's V,0.205,Small,Higher in readmitted,0.000000,0.000000,Yes
29,Discharge type,LAMA,12.88,19.48,6.60,Chi-square,Cramér's V,0.070,Negligible,Higher in readmitted,0.000000,0.000000,Yes
30,Discharge type,Recovered,78.44,72.34,-6.10,Chi-square,Cramér's V,0.070,Negligible,Lower in readmitted,0.000000,0.000000,Yes
31,Discharge type,Referred,8.68,8.18,-0.50,Chi-square,Cramér's V,0.070,Negligible,Lower in readmitted,0.000000,0.000000,Yes
32,Hospital,Apollo/Manipal (Private) Andhra Pradesh - 573,3.07,2.78,-0.29,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
33,Hospital,Apollo/Manipal (Private) Andhra Pradesh - 663,3.08,3.25,0.18,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
34,Hospital,Apollo/Manipal (Private) Andhra Pradesh - 963,2.95,2.87,-0.08,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
35,Hospital,Apollo/Manipal (Private) Andhra Pradesh - 986,3.04,3.06,0.03,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
36,Hospital,Apollo/Manipal (Private) Karnataka - 1018,3.12,2.81,-0.32,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
37,Hospital,Apollo/Manipal (Private) Karnataka - 999,2.97,3.32,0.35,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
38,Hospital,Apollo/Manipal (Private) Telangana - 514,3.06,3.32,0.27,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
39,Hospital,Apollo/Manipal (Private) Uttar Pradesh - 373,2.97,2.78,-0.19,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
40,Hospital,District Hospital Bihar - 142,3.09,3.05,-0.04,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
41,Hospital,District Hospital Bihar - 99,3.14,3.14,-0.00,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
42,Hospital,District Hospital Gujarat - 70,3.04,3.10,0.06,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
43,Hospital,District Hospital Kerala - 61,3.04,3.15,0.11,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
44,Hospital,District Hospital Madhya Pradesh - 67,3.09,3.06,-0.03,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
45,Hospital,District Hospital Odisha - 108,3.07,2.78,-0.29,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
46,Hospital,District Hospital Odisha - 146,2.85,2.90,0.05,Chi-square,Cramér's V,0.021,Negligible,Higher in readmitted,0.475765,0.634353,No
47,Hospital,District Hospital Rajasthan - 197,3.04,2.95,-0.08,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
48,Hospital,District Hospital Uttar Pradesh - 125,3.03,2.72,-0.31,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No
49,Hospital,District Hospital Uttar Pradesh - 191,3.11,3.06,-0.05,Chi-square,Cramér's V,0.021,Negligible,Lower in readmitted,0.475765,0.634353,No

In [68]:
# ============================================================
# 19. VARIABLE-LEVEL STATISTICAL SUMMARY
# ============================================================

continuous_summary = continuous_table[
    [
        "Variable",
        "Test",
        "Effect Size Type",
        "Effect Size",
        "Effect Size Interpretation",
        "P-value",
        "Adjusted P-value",
        "Adjusted Significant"
    ]
].copy()


categorical_summary = categorical_pvalues.merge(
    categorical_table[
        [
            "Variable",
            "Test",
            "Effect Size Type",
            "Effect Size",
            "Effect Size Interpretation"
        ]
    ].drop_duplicates("Variable"),
    on="Variable",
    how="left"
)[
    [
        "Variable",
        "Test",
        "Effect Size Type",
        "Effect Size",
        "Effect Size Interpretation",
        "P-value",
        "Adjusted P-value",
        "Adjusted Significant"
    ]
]


statistical_summary = pd.concat(
    [
        continuous_summary,
        categorical_summary
    ],
    ignore_index=True
)

statistical_summary

,Variable,Test,Effect Size Type,Effect Size,Effect Size Interpretation,P-value,Adjusted P-value,Adjusted Significant
0,Age,Welch's t-test,Cohen's d,0.391782,Small,0.000000e+00,0.000000e+00,Yes
1,Comorbidity count,Welch's t-test,Cohen's d,0.564452,Moderate,0.000000e+00,0.000000e+00,Yes
2,Previous admissions,Welch's t-test,Cohen's d,0.395497,Small,1.883977e-246,3.453959e-246,Yes
3,Length of stay,Welch's t-test,Cohen's d,0.675005,Moderate,0.000000e+00,0.000000e+00,Yes
4,Procedures,Welch's t-test,Cohen's d,0.364918,Small,1.442982e-221,1.984100e-221,Yes
5,Charlson index,Welch's t-test,Cohen's d,0.509664,Moderate,0.000000e+00,0.000000e+00,Yes
6,HbA1c,Welch's t-test,Cohen's d,-0.057191,Negligible,2.001942e-09,2.202137e-09,Yes
7,Creatinine,Welch's t-test,Cohen's d,0.058881,Negligible,2.167692e-07,2.167692e-07,Yes
8,Haemoglobin,Welch's t-test,Cohen's d,-0.330622,Small,1.795173e-223,2.820987e-223,Yes
9,Systolic blood pressure,Welch's t-test,Cohen's d,0.218281,Small,1.016940e-97,1.242927e-97,Yes
10,Diagnosis count,Welch's t-test,Cohen's d,0.470275,Small,0.000000e+00,0.000000e+00,Yes
11,Gender,Chi-square,Cramér's V,0.003742,Negligible,6.018191e-01,6.565299e-01,No
12,Patient state,Chi-square,Cramér's V,0.013283,Negligible,5.425475e-01,6.510570e-01,No
13,Insurance type,Chi-square,Cramér's V,0.064462,Negligible,4.971046e-65,9.942091e-65,Yes
14,Admission type,Chi-square,Cramér's V,0.119912,Small,3.384434e-227,1.353773e-226,Yes
15,Ward type,Chi-square,Cramér's V,0.204948,Small,0.000000e+00,0.000000e+00,Yes
16,Discharge type,Chi-square,Cramér's V,0.069844,Negligible,1.475801e-77,4.427402e-77,Yes
17,Hospital,Chi-square,Cramér's V,0.020945,Negligible,4.757645e-01,6.343527e-01,No
18,Hospital state,Chi-square,Cramér's V,0.010575,Negligible,8.834375e-01,8.834375e-01,No
19,Hospital tier,Chi-square,Cramér's V,0.005217,Negligible,3.726119e-01,5.589179e-01,No
20,Teaching hospital,Chi-square,Cramér's V,0.005442,Negligible,1.427484e-01,2.447115e-01,No
21,BPL card,Chi-square,Cramér's V,0.064473,Negligible,1.556445e-67,3.735468e-67,Yes
22,Primary diagnosis category,Chi-square,Cramér's V,0.137340,Small,7.608228e-288,4.564937e-287,Yes

In [69]:
# ============================================================
# 20. STATISTICAL SIGNIFICANCE SUMMARY
# ============================================================

print("Nominal significance (p < 0.05)")
print("--------------------------------")

print(
    "Continuous variables:",
    (continuous_table["P-value"] < 0.05).sum(),
    "of",
    len(continuous_table)
)

print(
    "Categorical variables:",
    (
        categorical_pvalues["P-value"] < 0.05
    ).sum(),
    "of",
    len(categorical_pvalues)
)


print("\nFDR-adjusted significance")
print("--------------------------------")

print(
    "Continuous variables:",
    (
        continuous_table["Adjusted P-value"] < 0.05
    ).sum(),
    "of",
    len(continuous_table)
)

print(
    "Categorical variables:",
    (
        categorical_pvalues["Adjusted P-value"] < 0.05
    ).sum(),
    "of",
    len(categorical_pvalues)
)

Nominal significance (p < 0.05)
--------------------------------
Continuous variables: 11 of 11
Categorical variables: 6 of 12

FDR-adjusted significance
--------------------------------
Continuous variables: 11 of 11
Categorical variables: 6 of 12

In [70]:
# ============================================================
# 21. CHI-SQUARE ASSUMPTION CHECK
# ============================================================

chi_square_quality = (
    categorical_table[
        [
            "Variable",
            "Minimum Expected Count",
            "Percent Expected Counts <5"
        ]
    ]
    .drop_duplicates("Variable")
    .copy()
)

chi_square_quality["Expected Count Flag"] = np.where(
    chi_square_quality["Percent Expected Counts <5"] > 20,
    "Review",
    "Adequate"
)

display(chi_square_quality)

,Variable,Minimum Expected Count,Percent Expected Counts <5,Expected Count Flag
0,Gender,119.302487,0.0,Adequate
3,Patient state,386.814758,0.0,Adequate
18,Insurance type,1936.948547,0.0,Adequate
22,Admission type,1497.270170,0.0,Adequate
25,Ward type,430.255556,0.0,Adequate
29,Discharge type,996.423317,0.0,Adequate
32,Hospital,330.916671,0.0,Adequate
65,Hospital state,345.609883,0.0,Adequate
80,Hospital tier,2808.639276,0.0,Adequate
83,Teaching hospital,4912.962665,0.0,Adequate
85,BPL card,4066.825346,0.0,Adequate
87,Primary diagnosis category,416.520598,0.0,Adequate

In [71]:
# ============================================================
# 22. EXPORT TABLEAU-READY ANALYTICAL DATASET
# ============================================================

output_file = "clinical_readmission_analysis.csv"

clinical_analysis_table.to_csv(
    output_file,
    index=False
)

print(f"Saved: {output_file}")

Saved: clinical_readmission_analysis.csv

In [72]:
# ============================================================
# 23. DOWNLOAD CSV
# ============================================================

files.download(output_file)

In [73]:
# ============================================================
# 24. EXPORT VARIABLE-LEVEL SUMMARY
# ============================================================

summary_file = "clinical_readmission_statistical_summary.csv"

statistical_summary.to_csv(
    summary_file,
    index=False
)

print(f"Saved: {summary_file}")

files.download(summary_file)

Saved: clinical_readmission_statistical_summary.csv

## Interpretation and Limitations

This analysis identifies **unadjusted statistical associations** between selected patient, clinical, admission, insurance, hospital, and diagnosis characteristics and 30-day hospital readmission among the defined analytical population.

Statistical significance indicates evidence that an observed difference or association is unlikely to be explained by sampling variation alone under the statistical test assumptions. It does not establish causality or indicate that a variable is clinically important.

Effect sizes are therefore reported alongside p-values to provide additional context regarding the magnitude of observed differences or associations.

Because multiple variables are tested, Benjamini-Hochberg false discovery rate (FDR) adjustment is applied to the statistical results. Both nominal and FDR-adjusted significance should be considered when interpreting the findings.

The results should be viewed as a screening and analytical assessment rather than evidence of causal relationships. Variables identified through this analysis may warrant further investigation, visualization, clinical review, or consideration as candidate predictors in the separate predictive modeling workflow.

### Key Limitations

* The analyses are unadjusted and do not control for potential confounding variables.
* Statistical association does not establish causation.
* Statistical significance does not necessarily indicate clinical or operational importance.
* Multiple comparisons increase the possibility of false-positive findings; FDR adjustment is used to address this concern.
* Categorical variables with sparse expected cell counts require cautious interpretation of Chi-square results.
* The analysis population is restricted to secondary-diagnosis admissions and excludes expired admissions.
* Findings are based on the available analytical dataset and may not generalize beyond the population represented by the data.
* Clinical interpretation and intervention planning should incorporate subject-matter expertise and, where appropriate, further validation.

### Relationship to Predictive Modeling

This notebook addresses the **statistical association** component of the project.

The separate predictive modeling workflow addresses a different question: whether available patient and admission characteristics can be used to identify patients at higher predicted risk of 30-day readmission.

Therefore:

**Statistical analysis asks:**
*Which variables show evidence of association with readmission, and how large are the observed differences or associations?*

**Predictive modeling asks:**
*How well can available information identify patients at higher predicted risk of readmission?*

The two analyses are complementary but serve different purposes.